
const types = {
  // --- AUTH ---- //
  REGISTER_SUCCESS : "REGISTER_SUCCESS",
  REGISTER_FAIL : "REGISTER_FAIL",
  LOGIN_SUCCESS : "LOGIN_SUCCESS",
  LOGIN_FAIL : "LOGIN_FAIL",
  LOGOUT : "LOGOUT",
  SET_MESSAGE : "SET_MESSAGE",
  CLEAR_MESSAGE : "CLEAR_MESSAGE",
   // --- DASHBOARD ---- //
  DASHBOARD_SUCCESS : "DASHBOARD_SUCCESS",
  DASHBOARD_FAIL : "DASHBOARD_FAIL",
   // --- PROFIL ---- //
  PROFIL_SUCCESS : 'PROFIL_SUCCESS',
  PROFIL_FAIL : 'PROFIL_FAIL',
  PROFIL_UPDATE_SUCCESS : 'PROFIL_UPDATE_SUCCESS',
  PROFIL_UPDATE_FAIL : 'PROFIL_UPDATE_FAIL',
  PROFIL_DELETE_SUCCESS : 'PROFIL_DELETE_SUCCESS',
  PROFIL_DELETE_FAIL : 'PROFIL_DELETE_FAIL',
   // --- ACTIVITY ---- //
  ACTIVITY_SUCCESS : 'ACTIVITY_SUCCESS',
  ACTIVITY_FAIL : 'ACTIVITY_FAIL',
   // --- CONTACT ---- //
  GET_ALL_CONTACT_SUCCESS : "GET_ALL_CONTACT_SUCCESS",
  GET_ALL_CONTACT_FAIL : "GET_ALL_CONTACT_FAIL",
  ADD_CONTACT_SUCCESS : "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAIL : "ADD_CONTACT_FAIL",
  DELETE_CONTACT_SUCCESS : "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAIL : "DELETE_CONTACT_FAIL",
  DELETE_ALL_CONTACT_SUCCESS : "DELETE_ALL_CONTACT_SUCCESS",
  DELETE_ALL_CONTACT_FAIL : "DELETE_ALL_CONTACT_FAIL",
   // --- CRYPTO ---- //
  GET_CRYPTO_SUCCESS : "GET_CRYPTO_SUCCESS",
  GET_CRYPTO_FAIL : "GET_CRYPTO_FAIL",
  GET_ALL_CRYPTO_SUCCESS : "GET_ALL_CRYPTO_SUCCESS",
  GET_ALL_CRYPTO_FAIL : "GET_ALL_CRYPTO_FAIL",
  BUY_CRYPTO_SUCCESS : "BUY_CRYPTO_SUCCESS",
  BUY_CRYPTO_FAIL : "BUY_CRYPTO_FAIL",
  TRANSFERT_CRYPTO_SUCCESS : "TRANSFERT_CRYPTO_SUCCESS",
  TRANSFERT_CRYPTO_FAIL : "TRANSFERT_CRYPTO_FAIL"
} 

export default types;